<?php

/**
 * @file
 * Contains dsu_c_text.module.
 */

/**
 * Implements hook_theme.
 */
function dsu_c_text_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__c_text' => [
      'template'  => 'paragraph--c-text',
      'base hook' => 'paragraphs',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for paragraph.html.twig.
 */
function dsu_c_text_preprocess_paragraph__c_text(&$variables) {
  // Load the library when the rendered element is a dsu_c_text Paragraph.
  $variables['#attached']['library'][] = 'dsu_c_text/general';
}
