<?php

/**
 * @file
 * Contains ln_c_cardgrid.module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function ln_c_cardgrid_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ln_c_cardgrid' => [
      'template'  => 'paragraph--ln-c-cardgrid',
      'base hook' => 'paragraph',
    ],
    'paragraph__ln_c_grid_card_item' => [
      'template'  => 'paragraph--ln-c-grid-card-item',
      'base hook' => 'paragraph',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ln_c_cardgrid_preprocess_paragraph__ln_c_cardgrid(&$variables) {
  $variables['#attached']['library'][] = 'ln_c_cardgrid/general';
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->hasField('field_c_cardgrid_view_mode') && !$paragraph->get('field_c_cardgrid_view_mode')->isEmpty()) {
    $variables['attributes']['class'][] = Html::getClass("viewmode--{$paragraph->get('field_c_cardgrid_view_mode')->value}");
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function ln_c_cardgrid_theme_suggestions_paragraph_alter(array &$suggestions, array $variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['elements']['#paragraph'];

  if ($paragraph->hasField('field_c_cardgrid_view_mode') && !$paragraph->get('field_c_cardgrid_view_mode')->isEmpty()) {
    $suggestions[] = "paragraph__viewmode__{$paragraph->get('field_c_cardgrid_view_mode')->value}";
    $suggestions[] = "paragraph__{$paragraph->bundle()}__viewmode__{$paragraph->get('field_c_cardgrid_view_mode')->value}";
  }
}
